# This is a basic workflow to help you get started with Actions

name: CI-Back

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the dev branch
  push:
    branches: [ ci-test ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# defaults:
#   run:
#     working-directory: ./back

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      - name: Checkout 
        uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.SUBMODULE_TOKEN }} 

#       - name: Checkout doogang submodule
#         uses: actions/checkout@v2
#         with:
#           repository: my-org/my-private-tools
#           token: ${{ secrets.GitHub_PAT }} 
      
      
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
      - name: Grant execute permisson for gradlew
        working-directory: ./back
        run: |
          pwd
          chmod +x gradlew
        shell: bash
        
      - name: Build with Gradle
        working-directory: ./back
        run: ./gradlew clean build
        shell: bash

      - name: Zip jar file
        working-directory: ./back/cocktailpick-api/build/libs
        run: |
          mv ../../../appspec.yml .
          mv ../../../deploy.sh .
          zip back.zip *.jar appspec.yml deploy.sh
          rm *.jar
          rm *.yml
          rm *.sh
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_IAM_MANAGER_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_IAM_MANAGER_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Transfer to S3 for serving static
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: cocktail-pick-back-bucket
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_IAM_MANAGER_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_IAM_MANAGER_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-northeast-2
          SOURCE_DIR: './back/cocktailpick-api/build/libs'
          
      - name: run code deploy
        run: >
          aws deploy create-deployment 
          --application-name cocktailpick-prod 
          --deployment-config-name CodeDeployDefault.OneAtATime 
          --deployment-group-name cocktailpick-deploy-group 
          --s3-location bucket=cocktail-pick-back-bucket,bundleType=zip,key=back.zip
