# This is a basic workflow to help you get started with Actions

name: CI-Back

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the dev branch
  push:
    branches: [ ci-test ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

defaults:
  run:
    working-directory: ./back

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Checkout guni submodule
        uses: actions/checkout@v2
        with:
          repository: KueNiYam/6rinkers-db-migration
          token: ${{ secrets.SUBMODULE_DB_MIGRATION }} 

#       - name: Checkout doogang submodule
#         uses: actions/checkout@v2
#         with:
#           repository: my-org/my-private-tools
#           token: ${{ secrets.GitHub_PAT }} 
      
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
      - name: Grant execute permisson for gradlew
#         working-directory: ./back
        run: chmod +x gradlew
        shell: bash
        
      - name: Build with Gradle
#         working-directory: ./back
        run: ./gradlew clean build
        shell: bash

    
